### ISSUE TITLE
Rule execution ordering

### ISSUE THREAD

**Issue by redhatrises** [scapcommunity/XCCDF#18]
When a profile exists in XCCDF or DS, the scanner should be required to follow the execution order of the rules in the profile. This is so that authors can dictate scan order for proper rule remediation in addition to being opinionated or needing to order checking as well.

**Comment by djhaynes** [comment]
Does DS mean "data stream"?

**Comment by redhatrises** [comment]
@djhaynes DS does mean data stream.

**Comment by DavidRies** [comment]
Currently, there's no requirement that rules be assessed one-at-a-time. So, implementations may assess rules in parallel. And, however/whenever rules are assessed may not dictate when remediations are applied. For example, an implementation may evaluation all the rules, present results and remediation options to use and allow the user to select which remediations to apply and when to apply them.

It sounds like the issue here is that some remediations may have a dependency on other remediations. Is that right? If so--if this is just about remediation dependency--perhaps we should focus on that and not on rule ordering. For example, we could add a requirement to #8 that remediations support dependency along with an example illustrating the need?

**Comment by redhatrises** [comment]
I think both is the answer. There are needs to order rule checking (which can be set for parallel processing as well) in addition to remediation dependency handling.

**Comment by DavidRies** [comment]
Can you give an example of when rule order checking is needed? I haven't encountered that.

**Comment by redhatrises** [comment]
Need to address process handling of Groups and Rules.

**Comment by solind** [comment]
Let me give a concrete example to illustrate our confusion with this proposal.

Typically an XCCDF benchmark contains references to OVAL content.  Some implementations (including some of our own customers) interpret the XCCDF and profile, and generate a list of OVAL definitions that must be interpreted.  Then they pass this list to an OVAL interpreter, along with the OVAL content.  Maybe there is even an external_variables input containing exported XCCDF values thrown into the mix.

The OVAL interpreter generates OVAL results XML, then that is ingested and rule results are determined.

So, what does "order" mean in terms of rule checking in the above context?  There is no order.  The order is arbitrary.  In order to impose order, it would be necessary to run the interpreter exactly once for every XCCDF rule.  This would be unnecessarily slow.

XCCDF checks are supposed to check configurations, not make configuration changes.  If that is the case, then the order in which checks are performed should practically never matter.  (The only case I can think of is if perhaps some checks might take a really long time but not be very important, and you need to perform your checks in a limited time box, so you'd want to run those checks last, only if there is sufficient time remaining -- but this is an edge case, and if we care about it there are better ways of addressing it).

So again, please, where does the requirement for ordering checks come from?

**Comment by redhatrises** [comment]
This capability has been requested by many of our security customers who don't want arbitrary OVAL execution and want a vary specific profile-ordered rule process (and control over that) for differing edge reasons. Obviously, this has no affect on OVAL-only scanning. Also, this is an optional requirement so it shouldn't affect or even have to be supported by those who don't have an operational need for it.

**Comment by DavidRies** [comment]
Can you give one example of an edge case where an end-user would want control over the rule assessment and why? I'm having trouble understanding what that would even mean and a concrete example might really help.

**Comment by solind** [comment]
It isn't obvious to me that this would have no impact on OVAL scanning. OpenSCAP currently evaluates OVAL definitions one-at-a-time, I believe in document order. I'm not sure what other scanners do, but there is no implication in the specification currently that checks be performed in any particular order.

If this is something tied to a custom check system, then shouldn't ordering be something that is delegated to that check system?

**Comment by DavidRies** [comment]
The first comment on this Issue mentions assessment and remediation. I think it might help to look at these separately.

## Assessment (Checking)
The assessment of Rules, which as we all know is the primary use case for XCCDF, is designed to be "read-only" and rule evaluation order (including whether performed sequentially or in parallel or using pre-collected check results, etc.) should not have any impact on the results. The order should not impact what is assessed or what the results should be based on check evaluation. 

So, if prescribing the rule evaluation order does not change the configuration guidance, it *only* impacts the implementation. The specification is intentionally silent on things like that. This allows innovation in the engine space and separates concerns appropriately (content authors focus on documenting the guidance, engine buildings focus on implementing it).

Now, I know many end-users care deeply about how these rules are implemented (performance, scalability, resource consumption, deployment concerns, etc.). I'm guessing that the edge case end-users who want to run rule assessment sequentially in a prescribed order want finer control over resource consumption. If so, that's great! I'm all for it. Whichever engine developers have those customers can add a capability to support it (i.e. an engine configuration setting "evaluate rules in profile order"). Then, this behavior could be controlled at scan-time. Engine users could even do something more interesting like allowing end users to "limit RAM consumption to 100MB" and then have the engine internally optimize.

If we encode assessment order in the guidance, then every end user who uses a compliant engine to run this profile will have to run these rules in order even though it has no impact on the results. That would be bad for many end users. We have end users scanning large environments in small scan windows by using significant resources/parallelism. If our standards-compliant engine has to run these rules sequentially, it would have an enormous negative impact on the performance characteristics of those scans.

## Remediation
Remediation is different. It changes the system and order may very well matter. It depends on how the remediations are constructed. Remediations typically have dependencies (e.g. OS patch 1.1.3 can only be installed if the system has been already upgraded to at least 1.1.0). 

However, because Benchmarks can be Tailored, content authors do know which Rules will be run by end users. If a Benchmark is written such that Rule 2's remediation requires Rule 1's remediation... what happens if the content is Tailored to only select Rule 2?

One idea is to add dependency fields (elements/attributes) to XCCDF fix/fixtext elements, but... I think that's a mistake. All of the remediation technologies I'm familiar with already handle dependencies (and in different ways).

I suggest we clarify the documentation to make it explicit that when adding remediations into XCCDF, content authors should consider that rules may be evaluated in any order and that any subset of rules may be evaluated and should therefore handle dependency checking/resolution within the remediation itself (i.e. the script should check for its decencies and install them or fail as appropriate).

-David

**Comment by redhatrises** [comment]
As this minor request is considered too controversial, we are withdrawing this request and will solve the problem elsewhere.
